# fly.toml app configuration file for booking-site
# Full-stack Node.js + React + TypeScript app

app = 'booking-site'
primary_region = 'dfw'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[experimental]
  auto_rollback = true

[build]

[deploy]
  release_command = 'npm run db:migrate'
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = '10s'
    interval = '30s'
    method = 'GET'
    timeout = '5s'
    path = '/health'

[processes]
  app = 'node dist/server/index.js'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
